version: "3.8"

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my_network
    volumes:
      - ./api/src:/python-docker/src

  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
    name: codember-2023-network
